---
config: WV02

tasks:

  nb_spectralnet:
    tags:
      - ttc

  qradio:
    tags:
      - ttc

  dg_qfep:
    tags:
      - ttc

    variables:
      config: WV02-Operational

  wb_spectralnet_ch1:
    __plugin__: wb_spectralnet

    tags:
      - payload_ch1

    config: WV

  quantum_rx_ch1:
    __plugin__: quantum_rx

    tags:
      - payload_ch1

    variables:
      config: WV02_RH

  wb_spectralnet_ch2:
    __plugin__: wb_spectralnet

    tags:
      - payload_ch2

    config: WV

  quantum_rx_ch2:
    __plugin__: quantum_rx

    tags:
      - payload_ch2

    variables:
      config: WV02_LH

#  qmr:
#    __plugin__: qmr

#    tags:
#      - payload_ch1
#      - payload_ch2

#    config: WV02

  qdra_manager:
    __plugin__: qdra_manager

    capture_type: ca
    data_mode: wv1_wv2_wv3
    strip_trailing_byte_count: 16
    channel_bit_rate: 200
    processing_host_name: NW7
    spacecraft_config: WV2

    tags:
      - payload_ch1

  qdra_ch1:
    __plugin__: qdra

    variables:
      config: qdra1

    tags:
      - payload_ch1

  qdra_ch2:
    __plugin__: qdra

    variables:
      config: qdra2

    tags:
      - payload_ch1

  qdra_ch3:
    __plugin__: qdra

    variables:
      config: qdra3

    tags:
      - payload_ch2

  qdra_ch4:
    __plugin__: qdra

    variables:
      config: qdra4

    tags:
      - payload_ch2
