"""Legacy DART solver-record TDM writer.

Emits every field of the intermediate struct (``Sgp4Input``/``Rk89Input``)
as a TDM file, so the file is a complete, round-trippable record of what
was fed to the solver. Because the transport already uses CCSDS units
(km, km/s, Hz, degrees, UTC epochs), the mapping is a mechanical field copy:

- native TDM keywords for observations (``EPOCH``, ``DOPPLER_INSTANTANEOUS``,
  ``AZIMUTH``, ``ELEVATION``, ``RANGE``) and meta (``TIME_SYSTEM``,
  ``START_TIME``, ``STOP_TIME``, ``PARTICIPANT_1/2``, ``MODE``);
- ``USER_DEFINED_*`` keys for everything else (TLE, ECI state, force model,
  solver options, station coordinates), prefixed ``USER_DEFINED_STATION_<id>``
  for stations so ids with dashes stay legal key characters.

This is a solver diagnostic record, not a KSAT delivery template. KSAT
products use ``dart.io.ksat_tdm``.
"""

from __future__ import annotations

import datetime
from pathlib import Path

from dart.schema import (
    Rk89Input,
    Sgp4Input,
    SolverResult,
)

ORIGINATOR = "DART"
TDM_VERSION = "2.0"

SolverInput = Sgp4Input | Rk89Input


def _kv(key: str, value: str) -> str:
    return f"{key} = {value}"


def _keyify(text: str) -> str:
    """TDM keywords are alphanumeric/underscore — map anything else to '_'."""
    return "".join(c if c.isalnum() else "_" for c in text)


def format_epoch(unix: float) -> str:
    """Unix seconds -> ISO 8601 UTC with milliseconds and a Z suffix."""
    dt = datetime.datetime.fromtimestamp(unix, tz=datetime.UTC)
    return f"{dt.strftime('%Y-%m-%dT%H:%M:%S')}.{dt.microsecond // 1000:03d}Z"


def _meta_lines(inp: SolverInput, creation_date: datetime.datetime) -> list[str]:
    lines = [
        _kv("CCSDS_TDM_VERS", TDM_VERSION),
        _kv("COMMENT", "Generated by DART"),
        _kv("CREATION_DATE", format_epoch(creation_date.timestamp())),
        _kv("ORIGINATOR", ORIGINATOR),
        "",
        "META_START",
        _kv("TIME_SYSTEM", "UTC"),
        _kv("MODE", inp.mode),
        _kv(
            "START_TIME",
            format_epoch(min(o.epoch_unix for o in inp.observations)),
        ),
        _kv(
            "STOP_TIME",
            format_epoch(max(o.epoch_unix for o in inp.observations)),
        ),
        _kv("PARTICIPANT_1", inp.spacecraft_id or "UNKNOWN"),
    ]

    for station in inp.stations:
        key = _keyify(station.id)
        lines.append(_kv("PARTICIPANT_2", station.id))
        if station.name:
            lines.append(_kv(f"USER_DEFINED_STATION_{key}_NAME", station.name))
        lines.append(_kv(f"USER_DEFINED_STATION_{key}_LAT_DEG", repr(station.lat_deg)))
        lines.append(_kv(f"USER_DEFINED_STATION_{key}_LON_DEG", repr(station.lon_deg)))
        lines.append(_kv(f"USER_DEFINED_STATION_{key}_ALT_KM", repr(station.alt_km)))

    opts = inp.options
    lines.append(_kv("USER_DEFINED_REF_FRAME", opts.ref_frame))
    lines.append(_kv("USER_DEFINED_MAX_ITERATIONS", str(opts.max_iterations)))
    lines.append(_kv("USER_DEFINED_TOLERANCE", repr(opts.tolerance)))

    if isinstance(inp, Sgp4Input):
        lines.append(_kv("USER_DEFINED_TLE_LINE_1", inp.tle.line1))
        lines.append(_kv("USER_DEFINED_TLE_LINE_2", inp.tle.line2))
        fit = inp.fit
        lines.append(_kv("USER_DEFINED_FIT_MODEL", fit.model))
        lines.append(_kv("USER_DEFINED_PASS_IDS", " ".join(fit.pass_ids)))
        lines.append(
            _kv("USER_DEFINED_NOMINAL_CENTER_FREQUENCY_HZ", repr(fit.nominal_center_frequency_hz))
        )
        lines.append(_kv("USER_DEFINED_LOSS", fit.loss))
        lines.append(_kv("USER_DEFINED_LOSS_SCALE", repr(fit.loss_scale)))
    elif isinstance(inp, Rk89Input):
        fm = inp.force_model
        lines.append(_kv("USER_DEFINED_STATE_EPOCH", format_epoch(inp.epoch_unix)))
        lines.append(
            _kv("USER_DEFINED_POS_KM", " ".join(repr(v) for v in inp.pos_km))
        )
        lines.append(
            _kv("USER_DEFINED_VEL_KM_S", " ".join(repr(v) for v in inp.vel_km_s))
        )
        lines.append(_kv("USER_DEFINED_GRAVITY_DEG", str(fm.gravity_deg)))
        lines.append(_kv("USER_DEFINED_THIRD_BODY", str(fm.third_body).upper()))
        lines.append(_kv("USER_DEFINED_SRP", str(fm.srp).upper()))
        lines.append(_kv("USER_DEFINED_STEP_S", repr(fm.step_s)))

    lines.append("META_STOP")
    lines.append("")
    return lines


def _observation_block(station_id: str, rows: list) -> list[str]:
    lines = [
        "OBSERVATION_START",
        _kv("PARTICIPANT_2", station_id),
    ]
    for obs in rows:
        lines.append(_kv("EPOCH", format_epoch(obs.epoch_unix)))
        lines.append(_kv("USER_DEFINED_CONTACT_ID", obs.contact_id))
        lines.append(_kv("DOPPLER_INSTANTANEOUS", f"{obs.doppler_hz:.6f}"))
        lines.append(_kv("AZIMUTH", f"{obs.azimuth_deg:.6f}"))
        lines.append(_kv("ELEVATION", f"{obs.elevation_deg:.6f}"))
        if obs.range_km is not None:
            lines.append(_kv("RANGE", f"{obs.range_km:.3f}"))
    lines.append("OBSERVATION_STOP")
    return lines


def write_tdm(
    inp: SolverInput,
    path: str | Path | None = None,
    *,
    creation_date: datetime.datetime | None = None,
) -> str:
    """Serialize ``inp`` to a CCSDS TDM string.

    ``path`` optionally writes the file; ``creation_date`` pins the header
    timestamp (tests use this for golden output). Raises ``ValueError`` on an
    input with no observations (a TDM requires START/STOP times).
    """
    if not inp.observations:
        raise ValueError("cannot write TDM for an input with no observations")

    created = creation_date or datetime.datetime.now(datetime.UTC)
    lines = _meta_lines(inp, created)

    by_station: dict[str, list] = {}
    for obs in inp.observations:
        by_station.setdefault(obs.station_id, []).append(obs)

    for station_id in inp.stations:
        rows = by_station.get(station_id.id)
        if rows:
            lines.extend(_observation_block(station_id.id, rows))
            lines.append("")

    text = "\n".join(lines).rstrip() + "\n"
    if path is not None:
        Path(path).write_text(text, encoding="utf-8")
    return text


def write_result_tdm(
    result: SolverResult,
    path: str | Path | None = None,
    *,
    creation_date: datetime.datetime | None = None,
) -> str:
    """Serialize a ``SolverResult`` to a minimal TDM (solved state + stats).

    Native keywords for what TDM knows (epoch/state), ``USER_DEFINED_*`` for
    solver statistics and residuals.
    """
    created = creation_date or datetime.datetime.now(datetime.UTC)
    lines = [
        _kv("CCSDS_TDM_VERS", TDM_VERSION),
        _kv("COMMENT", "Generated by DART (solver result)"),
        _kv("CREATION_DATE", format_epoch(created.timestamp())),
        _kv("ORIGINATOR", ORIGINATOR),
        "",
        "META_START",
        _kv("TIME_SYSTEM", "UTC"),
        _kv("MODE", result.mode),
        _kv("EPOCH", format_epoch(result.epoch_unix)),
        _kv("USER_DEFINED_SUCCESS", str(result.success).upper()),
        _kv("USER_DEFINED_CONVERGED", str(result.converged).upper()),
        _kv("USER_DEFINED_ITERATIONS", str(result.iterations)),
        _kv("USER_DEFINED_RMS", repr(result.rms)),
        _kv("USER_DEFINED_MESSAGE", result.message),
        _kv("USER_DEFINED_POS_KM", " ".join(repr(v) for v in result.pos_km)),
        _kv("USER_DEFINED_VEL_KM_S", " ".join(repr(v) for v in result.vel_km_s)),
        _kv(
            "USER_DEFINED_COVARIANCE",
            " ".join(repr(v) for v in result.covariance),
        ),
        _kv("USER_DEFINED_RESIDUALS", " ".join(repr(v) for v in result.residuals)),
        _kv("USER_DEFINED_OBJECTIVE", repr(result.objective)),
        _kv("USER_DEFINED_FUNCTION_EVALUATIONS", str(result.function_evaluations)),
        _kv("USER_DEFINED_GRADIENT_EVALUATIONS", str(result.gradient_evaluations)),
        _kv("USER_DEFINED_PARAMETER_NAMES", " ".join(result.parameter_names)),
        _kv("USER_DEFINED_PARAMETERS", " ".join(repr(v) for v in result.parameters)),
        _kv(
            "USER_DEFINED_PARAMETER_COVARIANCE",
            " ".join(repr(v) for v in result.parameter_covariance),
        ),
        _kv("USER_DEFINED_COVARIANCE_RANK", str(result.covariance_rank)),
        "META_STOP",
    ]
    if result.fitted_tle is not None:
        lines[-1:-1] = [
            _kv("USER_DEFINED_FITTED_TLE_LINE_1", result.fitted_tle.line1),
            _kv("USER_DEFINED_FITTED_TLE_LINE_2", result.fitted_tle.line2),
        ]
    text = "\n".join(lines).rstrip() + "\n"
    if path is not None:
        Path(path).write_text(text, encoding="utf-8")
    return text
