---
version: '3'

services:
  access_proxy:
    image: $ACCESS_PROXY_IMAGE
    container_name: access_proxy
    restart: always
    ports:
      - 5000:5000
      - $PROXY_HOST:8080:8080
      - $PROXY_HOST:8082:8082
      - $PROXY_HOST:8079:8079
      - $PROXY_HOST:8008:8008
      - $PROXY_HOST:3000:3000
      - $PROXY_HOST:3001:3001
      - $PROXY_HOST:3002:3002
      - $PROXY_HOST:3020:3020
      - $PROXY_HOST:3050:3050
      - $PROXY_HOST:3070:3070
      - $PROXY_HOST:50180:50180
      - $PROXY_HOST:50190:50190
      - $PROXY_HOST:50210:50210
      - $PROXY_HOST:56030:56030
      - $PROXY_HOST:56000:56000
      - $PROXY_HOST:51101:51101
      - $PROXY_HOST:51103:51103

    environment:
      - QRADIO_HOST
      - QMR_HOST
      - PROXY_MODE
      - MC_PORT=9999
      - MC_HOST
      - SPECTRUM_PORT=8007
      - SPECTRUM_HOST
      
  control_api:
    image: $CONTROL_API_IMAGE
    container_name: control_api
    restart: always

    ports:
      - 9999:5000

  spectrum_plot:
    image: $SPECTRUM_PLOT_IMAGE
    container_name: spectrum_plot
    restart: always

    ports:
      - 8007:80

    environment:
      - QRADIO_HOST
      - QMR_HOST
      - SPECNET_HOST
    
  
