---
config: WV2_NB
acu_config: WV2


tasks:

  spectralnet:
    tags:
      - ttc

    variables:
      config: TG2

  qradio:
    tags:
      - ttc

  dg_qfep:
    tags:
      - ttc

    variables:
      config: WV03-Operational

      
