config: NAOS1

services:

  cortex_crt1:
    tags:
    - SU
    - SD
    document_id:
      M1: 1
      M2: 2
    menu_id: 3
    uplink:
      uplink_channel: 1
      sweep:
        blind_acq_timeout: 180
        idle_pattern_channel: 1
        sweep_duration: 12
      doppler_compensation:
        start_doppler: True
        carrier_frequency: 2059000000
    doppler_record_combiner_channel: 1    
    sle:
      uplink:
        cltu_service_instance: "sagr=SAGR.spack=SPACK.fsl-fg=FSL-FG.cltu=cltu1"
      downlink:
        ert_offset: 0
        online_buffer_size: "2"
        telemetry_channel: 1
        service_instance_raf: "sagr=SAGR.spack=SPACK.rsl-fg=RSL-FG.raf=onlt1"
        service_instance_rcf: "sagr=SAGR.spack=SPACK.rsl-fg=RSL-FG.rcf=onlt1"
    telemetry_channel: 1    
    data_delivery:
      crt_info: True
      frame_length: 1119
      filter_vcids: [ 0,1,7,-1 ]
      filename: "NAOS1_SG50_{aos}_VCID{vcid}.tlm"
      destination:
        host: "172.23.99.11"
        path: "/data/customers/luxsys/TEST/telemetry/"
      

  cortex_crt2:
    tags:
    - SU
    - SD
    document_id:
      M1: 1
      M2: 2
    menu_id: 3
    uplink:
      uplink_channel: 1
      sweep:
        blind_acq_timeout: 180
        idle_pattern_channel: 1
        sweep_duration: 12
      doppler_compensation:
        start_doppler: True
        carrier_frequency: 2059000000
    doppler_record_combiner_channel: 1    
    sle:
      uplink:
        cltu_service_instance: "sagr=SAGR.spack=SPACK.fsl-fg=FSL-FG.cltu=cltu1"
      downlink:
        ert_offset: 0
        online_buffer_size: "2"
        telemetry_channel: 1
        service_instance_raf: "sagr=SAGR.spack=SPACK.rsl-fg=RSL-FG.raf=onlt1"
        service_instance_rcf: "sagr=SAGR.spack=SPACK.rsl-fg=RSL-FG.rcf=onlt1"
    telemetry_channel: 1    
    data_delivery:
      crt_info: False
      frame_length: 1119
      filter_vcids: [ 0,1,7 ]
      filename: "NAOS1_SG50_{aos}_VCID{vcid}_bck.tlm"
      destination:
        host: "172.23.99.11"
        path: "/data/customers/luxsys/TEST/telemetry/"


  orbital-ng:
    transmit_time_offset: 0
    hpa_input_attenuation: 3
    hpa_output_control: Test Termination
    autotrack: "Yes"
    rf_config_file: "NAOS1_S_RH.json"
    
  hypermatter:
    tags:
      - XD
      - SD

    write_moved_files_to_azure: True
    source:
      host: "10.103.0.71"
      path: "NAOS/Report"

    destination:
      host: "172.23.99.11"
      path: "/data/customers/luxsys/TEST/payload_data/"
  
  spaceport:
    tags:
      - XD
      - SD
    uplink_rf_switch:
      input_port: 1
      output_port: 1