[schedulers]
HA_scheduler ansible_host=10.101.15.20 
SG_scheduler1 ansible_host=10.103.0.80 
SG_scheduler2 ansible_host=10.103.0.85 
NZ_scheduler ansible_host=10.121.102.80 ansible_python_interpreter=/usr/bin/python3.8
PA_scheduler ansible_host=10.117.13.25 
TR_scheduler ansible_host=192.168.211.72 
LB_scheduler ansible_host=10.119.102.30  
PL_scheduler ansible_host=10.120.102.50 
MA_scheduler ansible_host=10.101.42.20 
AT_scheduler ansible_host=10.124.102.241 
TA_scheduler ansible_host=172.22.96.80 ansible_python_interpreter=/usr/bin/python3.8
MN_scheduler ansible_host=10.126.102.80 ansible_python_interpreter=/usr/bin/python3.8
JJ_scheduler ansible_host=10.127.102.80 ansible_python_interpreter=/usr/bin/python3.8
IG4_scheduler ansible_host=10.110.127.210 ansible_python_interpreter=/usr/bin/python3
MN3_schduler ansible_host=10.141.127.212 ansible_python_interpreter=/usr/bin/python3

[schedulers:vars]
ansible_user=lite
ansible_python_interpreter=/usr/bin/python3.6
ctrl_config_production=master

[acus]
HA2 ansible_host=10.101.15.20 acu_user=ha2
PA50 ansible_host=10.117.13.25 acu_user=pa50
PA51 ansible_host=10.117.13.25 acu_user=pa51
SG42 ansible_host=10.103.0.80 acu_user=sg42
SG43 ansible_host=10.103.0.80 acu_user=sg43
SG71 ansible_host=10.103.0.80 acu_user=sg71
SG180 ansible_host=10.103.0.80 acu_user=sg180
SG181 ansible_host=10.103.0.85 acu_user=sg181
SG182 ansible_host=10.103.0.85 acu_user=sg182
SG183 ansible_host=10.103.0.85 acu_user=sg183
NZ2 ansible_host=10.121.102.80 acu_user=nz2 ansible_python_interpreter=/usr/bin/python3.8
TR4 ansible_host=192.168.211.72 acu_user=tr4
TR6 ansible_host=192.168.211.72 acu_user=tr6
TR8 ansible_host=192.168.211.72 acu_user=tr8
LB1 ansible_host=10.119.102.30 acu_user=lb1
PL2 ansible_host=10.120.102.50 acu_user=pl2
MA4 ansible_host=10.101.42.20 acu_user=ma4
#AT1 ansible_host=10.124.102.241 acu_host=at1

[acus:vars]
ansible_user=lite
ansible_python_interpreter=/usr/bin/python3.6
acu_config=master

