---    
## Configs, assues that everything is setup
- name: Deploy acu configs
  
  become_user: "{{ acu_user }}"
  git:
    accept_hostkey: yes
    repo: git@gitlab.ksat.no:sop-dev/ksat-app-orbital.git
    dest: /home/{{ acu_user }}/ksat-app-orbital
    version:  "{{ acu_config }}" 
