# This file is generated. Do not edit it directly.
# Source: contracts/openapi/postprocessor-v0.1.json
# Generator: datamodel-code-generator==0.35.0

# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
)


def _require_datetime_string(value: object) -> object:
    if not isinstance(value, str):
        raise ValueError("date-time values must be strings")
    return value


StrictAwareDatetime = Annotated[AwareDatetime, BeforeValidator(_require_datetime_string)]


class CandidateStatus(Enum):
    pending = "pending"
    optimizing = "optimizing"
    postprocessing = "postprocessing"
    succeeded = "succeeded"
    unhealthy = "unhealthy"
    ineligible = "ineligible"
    failed = "failed"


class Cartesian3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: Annotated[StrictFloat, Field(title="X")]
    y: Annotated[StrictFloat, Field(title="Y")]
    z: Annotated[StrictFloat, Field(title="Z")]


class Covariance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    matrix: Annotated[list[list[StrictFloat]], Field(min_length=1, title="Matrix")]
    parameter_order: Annotated[list[str], Field(min_length=1, title="Parameter Order")]


class DatasetQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contact_ids: Annotated[list[str], Field(title="Contact Ids")] = []
    end_time: Annotated[StrictAwareDatetime | None, Field(title="End Time")] = None
    maximum_doppler_hz: Annotated[StrictFloat, Field(title="Maximum Doppler Hz")] = 100000.0
    minimum_doppler_hz: Annotated[StrictFloat, Field(title="Minimum Doppler Hz")] = -100000.0
    minimum_ebn0_db: Annotated[StrictFloat, Field(title="Minimum Ebn0 Db")] = 0.0
    minimum_elevation_deg: Annotated[StrictFloat, Field(title="Minimum Elevation Deg")] = 1.0
    require_lock: Annotated[StrictBool, Field(title="Require Lock")] = False
    spacecraft_id: Annotated[str | None, Field(title="Spacecraft Id")] = None
    start_time: Annotated[StrictAwareDatetime | None, Field(title="Start Time")] = None


class EvidenceClass(Enum):
    residual_only = "residual_only"
    reference_ephemeris = "reference_ephemeris"


class JacobianCondition(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=1.0, title="Jacobian Condition")]


class JacobianRank(RootModel[StrictInt]):
    root: Annotated[StrictInt, Field(ge=0, title="Jacobian Rank")]


class RobustCost(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, title="Robust Cost")]


class WeightedSsr(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, title="Weighted Ssr")]


class FitDiagnostics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    at_bound: Annotated[StrictBool | None, Field(title="At Bound")] = None
    healthy: Annotated[StrictBool, Field(title="Healthy")]
    jacobian_condition: Annotated[JacobianCondition | None, Field(title="Jacobian Condition")] = (
        None
    )
    jacobian_rank: Annotated[JacobianRank | None, Field(title="Jacobian Rank")] = None
    message: Annotated[str, Field(title="Message")]
    observations_used: Annotated[StrictInt, Field(ge=0, title="Observations Used")]
    robust_cost: Annotated[RobustCost | None, Field(title="Robust Cost")] = None
    success: Annotated[StrictBool, Field(title="Success")]
    weighted_ssr: Annotated[WeightedSsr | None, Field(title="Weighted Ssr")] = None


class InformationCriterion(Enum):
    bic = "bic"
    aic = "aic"
    aicc = "aicc"


class RobustLoss(Enum):
    linear = "linear"
    soft_l1 = "soft_l1"
    huber = "huber"
    cauchy = "cauchy"
    arctan = "arctan"


class MeanElementsTwoParameterMetaparameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    doppler_standard_deviation_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Doppler Standard Deviation Hz")
    ] = 500.0
    mean_anomaly_half_width_rad: Annotated[
        StrictFloat, Field(gt=0.0, title="Mean Anomaly Half Width Rad")
    ] = 0.5
    mean_motion_half_width_rad_min: Annotated[
        StrictFloat, Field(gt=0.0, title="Mean Motion Half Width Rad Min")
    ] = 0.002
    model: Annotated[Literal["mean_elements_two_parameter"], Field(title="Model")]
    pass_bias_bounds_hz: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Pass Bias Bounds Hz")
    ] = [-100000.0, 100000.0]
    qmc_samples: Annotated[StrictInt, Field(ge=0, le=4096, title="Qmc Samples")] = 64
    robust_loss: Annotated[RobustLoss, Field(title="Robust Loss")] = RobustLoss.cauchy
    robust_scale_hz: Annotated[StrictFloat, Field(gt=0.0, title="Robust Scale Hz")] = 500.0


class PhaseCalibrationProvenance(RootModel[str]):
    root: Annotated[str, Field(max_length=500, title="Phase Calibration Provenance")]


class MetricGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metrics: Annotated[
        dict[str, StrictFloat | StrictInt | StrictBool | None], Field(title="Metrics")
    ]


class ObservableChannel(Enum):
    doppler = "doppler"
    phase_difference = "phase_difference"


class RobustWeight(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, title="Robust Weight")]


class ObservableResidual(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel: ObservableChannel
    consumed: Annotated[StrictBool, Field(title="Consumed")]
    predicted: Annotated[StrictFloat | None, Field(title="Predicted")] = None
    residual: Annotated[StrictFloat | None, Field(title="Residual")] = None
    robust_weight: Annotated[RobustWeight | None, Field(title="Robust Weight")] = None


class OemEncoding(Enum):
    kvn = "kvn"
    xml = "xml"


class OptimizerModel(Enum):
    time_offset = "time_offset"
    time_offset_pass_bias = "time_offset_pass_bias"
    time_offset_frequency_pass_bias = "time_offset_frequency_pass_bias"
    mean_elements_two_parameter = "mean_elements_two_parameter"


class PassDopplerBias(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bias_hz: Annotated[StrictFloat, Field(title="Bias Hz")]
    pass_id: Annotated[str, Field(max_length=200, min_length=1, title="Pass Id")]


class PipelineStage(Enum):
    acquisition = "acquisition"
    optimization = "optimization"
    postprocessing = "postprocessing"
    selection = "selection"
    persistence = "persistence"


class PointingSource(Enum):
    measured = "measured"
    commanded = "commanded"
    unknown = "unknown"


class ResidualRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channels: Annotated[list[ObservableResidual], Field(min_length=1, title="Channels")]
    measurement_id: Annotated[str, Field(max_length=200, min_length=1, title="Measurement Id")]


class RunStatus(Enum):
    queued = "queued"
    acquiring = "acquiring"
    optimizing = "optimizing"
    postprocessing = "postprocessing"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"


class SelectionScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    criterion: InformationCriterion
    eligible: Annotated[StrictBool, Field(title="Eligible")]
    fitted_parameter_count: Annotated[StrictInt, Field(ge=1, title="Fitted Parameter Count")]
    observations: Annotated[StrictInt, Field(ge=0, title="Observations")]
    residual_sum_squares_hz2: Annotated[
        StrictFloat, Field(ge=0.0, title="Residual Sum Squares Hz2")
    ]
    score: Annotated[StrictFloat | None, Field(title="Score")] = None


class StageError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error_type: Annotated[str, Field(max_length=200, min_length=1, title="Error Type")]
    message: Annotated[str, Field(max_length=2000, min_length=1, title="Message")]
    stage: PipelineStage


class TLEData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    line1: Annotated[str, Field(max_length=100, min_length=60, title="Line1")]
    line2: Annotated[str, Field(max_length=100, min_length=60, title="Line2")]
    name: Annotated[str, Field(max_length=200, min_length=1, title="Name")] = "DART-OBJECT"


class TdmDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(min_length=1, title="Content")]
    media_type: Annotated[Literal["application/ccsds-tdm-kvn"], Field(title="Media Type")] = (
        "application/ccsds-tdm-kvn"
    )
    sha256: Annotated[str, Field(pattern="^[0-9a-f]{64}$", title="Sha256")]


class TimeOffsetFrequencyPassBiasMetaparameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    center_frequency_correction_bounds_hz: Annotated[
        list[StrictFloat],
        Field(max_length=2, min_length=2, title="Center Frequency Correction Bounds Hz"),
    ] = [-100000.0, 100000.0]
    doppler_standard_deviation_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Doppler Standard Deviation Hz")
    ] = 500.0
    model: Annotated[Literal["time_offset_frequency_pass_bias"], Field(title="Model")]
    pass_bias_bounds_hz: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Pass Bias Bounds Hz")
    ] = [-100000.0, 100000.0]
    qmc_samples: Annotated[StrictInt, Field(ge=0, le=4096, title="Qmc Samples")] = 64
    robust_loss: Annotated[RobustLoss, Field(title="Robust Loss")] = RobustLoss.cauchy
    robust_scale_hz: Annotated[StrictFloat, Field(gt=0.0, title="Robust Scale Hz")] = 500.0
    time_offset_bounds_s: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Time Offset Bounds S")
    ] = [-120.0, 120.0]


class TimeOffsetFrequencyPassBiasParameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    center_frequency_correction_hz: Annotated[
        StrictFloat, Field(title="Center Frequency Correction Hz")
    ]
    model: Annotated[Literal["time_offset_frequency_pass_bias"], Field(title="Model")] = (
        "time_offset_frequency_pass_bias"
    )
    pass_biases: Annotated[list[PassDopplerBias], Field(min_length=1, title="Pass Biases")]
    time_offset_s: Annotated[StrictFloat, Field(title="Time Offset S")]


class TimeOffsetMetaparameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    doppler_standard_deviation_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Doppler Standard Deviation Hz")
    ] = 500.0
    model: Annotated[Literal["time_offset"], Field(title="Model")]
    qmc_samples: Annotated[StrictInt, Field(ge=0, le=4096, title="Qmc Samples")] = 64
    robust_loss: Annotated[RobustLoss, Field(title="Robust Loss")] = RobustLoss.cauchy
    robust_scale_hz: Annotated[StrictFloat, Field(gt=0.0, title="Robust Scale Hz")] = 500.0
    time_offset_bounds_s: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Time Offset Bounds S")
    ] = [-120.0, 120.0]


class TimeOffsetParameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Annotated[Literal["time_offset"], Field(title="Model")] = "time_offset"
    time_offset_s: Annotated[StrictFloat, Field(title="Time Offset S")]


class TimeOffsetPassBiasMetaparameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    doppler_standard_deviation_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Doppler Standard Deviation Hz")
    ] = 500.0
    model: Annotated[Literal["time_offset_pass_bias"], Field(title="Model")]
    pass_bias_bounds_hz: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Pass Bias Bounds Hz")
    ] = [-100000.0, 100000.0]
    qmc_samples: Annotated[StrictInt, Field(ge=0, le=4096, title="Qmc Samples")] = 64
    robust_loss: Annotated[RobustLoss, Field(title="Robust Loss")] = RobustLoss.cauchy
    robust_scale_hz: Annotated[StrictFloat, Field(gt=0.0, title="Robust Scale Hz")] = 500.0
    time_offset_bounds_s: Annotated[
        list[StrictFloat], Field(max_length=2, min_length=2, title="Time Offset Bounds S")
    ] = [-120.0, 120.0]


class TimeOffsetPassBiasParameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Annotated[Literal["time_offset_pass_bias"], Field(title="Model")] = (
        "time_offset_pass_bias"
    )
    pass_biases: Annotated[list[PassDopplerBias], Field(min_length=1, title="Pass Biases")]
    time_offset_s: Annotated[StrictFloat, Field(title="Time Offset S")]


class MeanElementsTwoParameterParameters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean_anomaly_rad: Annotated[StrictFloat, Field(title="Mean Anomaly Rad")]
    mean_motion_rad_min: Annotated[StrictFloat, Field(gt=0.0, title="Mean Motion Rad Min")]
    model: Annotated[Literal["mean_elements_two_parameter"], Field(title="Model")] = (
        "mean_elements_two_parameter"
    )
    pass_biases: Annotated[list[PassDopplerBias], Field(min_length=1, title="Pass Biases")]


class Measurement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    antenna_azimuth_deg: Annotated[StrictFloat | None, Field(title="Antenna Azimuth Deg")] = None
    antenna_elevation_deg: Annotated[StrictFloat | None, Field(title="Antenna Elevation Deg")] = (
        None
    )
    applied_offset_s: Annotated[StrictFloat | None, Field(title="Applied Offset S")] = None
    doppler_hz: Annotated[StrictFloat | None, Field(title="Doppler Hz")] = None
    ebn0_db: Annotated[StrictFloat | None, Field(title="Ebn0 Db")] = None
    measurement_id: Annotated[str, Field(max_length=200, min_length=1, title="Measurement Id")]
    pass_id: Annotated[str, Field(max_length=200, min_length=1, title="Pass Id")]
    phase_baseline_itrf_m: Cartesian3 | None = None
    phase_calibration_provenance: Annotated[
        PhaseCalibrationProvenance | None, Field(title="Phase Calibration Provenance")
    ] = None
    phase_difference_rad: Annotated[StrictFloat | None, Field(title="Phase Difference Rad")] = None
    pointing_source: PointingSource = PointingSource.unknown
    quality_flags: Annotated[list[str], Field(title="Quality Flags")] = []
    spacecraft_id: Annotated[str, Field(max_length=200, min_length=1, title="Spacecraft Id")]
    station_id: Annotated[str, Field(max_length=200, min_length=1, title="Station Id")]
    station_position_itrf_m: Cartesian3
    time_tag: Annotated[StrictAwareDatetime, Field(title="Time Tag")]
    valid: Annotated[StrictBool, Field(title="Valid")] = True


class OemDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(min_length=1, title="Content")]
    encoding: OemEncoding
    sha256: Annotated[str, Field(pattern="^[0-9a-f]{64}$", title="Sha256")]


class OptimizerConfiguration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nominal_carrier_frequency_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Nominal Carrier Frequency Hz")
    ]
    reference_tle: TLEData
    spacecraft_id: Annotated[str, Field(max_length=200, min_length=1, title="Spacecraft Id")]


class OptimizerData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metaparameters: Annotated[
        TimeOffsetMetaparameters
        | TimeOffsetPassBiasMetaparameters
        | TimeOffsetFrequencyPassBiasMetaparameters
        | MeanElementsTwoParameterMetaparameters,
        Field(discriminator="model", title="Metaparameters"),
    ]
    nominal_carrier_frequency_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Nominal Carrier Frequency Hz")
    ]
    reference_tle: TLEData
    spacecraft_id: Annotated[str, Field(max_length=200, min_length=1, title="Spacecraft Id")]


class QualityResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    convergence: MetricGroup
    evidence_class: EvidenceClass
    residuals: MetricGroup
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"
    selection: SelectionScore
    truth: MetricGroup | None = None


class RunCreated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: Annotated[UUID, Field(title="Run Id")]
    status: RunStatus = RunStatus.queued


class CandidateMetaparameters(
    RootModel[
        TimeOffsetMetaparameters
        | TimeOffsetPassBiasMetaparameters
        | TimeOffsetFrequencyPassBiasMetaparameters
        | MeanElementsTwoParameterMetaparameters
    ]
):
    root: Annotated[
        TimeOffsetMetaparameters
        | TimeOffsetPassBiasMetaparameters
        | TimeOffsetFrequencyPassBiasMetaparameters
        | MeanElementsTwoParameterMetaparameters,
        Field(discriminator="model"),
    ]


class RunRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate_metaparameters: Annotated[
        list[CandidateMetaparameters], Field(min_length=1, title="Candidate Metaparameters")
    ]
    optimizer_configuration: OptimizerConfiguration
    pipeline: Annotated[Literal["batch_od"], Field(title="Pipeline")] = "batch_od"
    query: DatasetQuery
    reference_oem: OemDocument | None = None
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"
    selection_criterion: InformationCriterion = InformationCriterion.bic


class BatchRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    measurements: Annotated[list[Measurement], Field(min_length=1, title="Measurements")]
    optimizer_data: OptimizerData
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"


class BatchResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    consumed_channels: Annotated[
        list[ObservableChannel], Field(min_length=1, title="Consumed Channels")
    ]
    corrected_tle: TLEData | None = None
    covariance: Covariance
    diagnostics: FitDiagnostics
    effective_carrier_frequency_hz: Annotated[
        StrictFloat, Field(gt=0.0, title="Effective Carrier Frequency Hz")
    ]
    model: OptimizerModel
    parameters: Annotated[
        TimeOffsetParameters
        | TimeOffsetPassBiasParameters
        | TimeOffsetFrequencyPassBiasParameters
        | MeanElementsTwoParameterParameters,
        Field(discriminator="model", title="Parameters"),
    ]
    pass_ids: Annotated[list[str], Field(min_length=1, title="Pass Ids")]
    reference_tle: TLEData
    residuals: Annotated[list[ResidualRecord], Field(min_length=1, title="Residuals")]
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"


class CandidateRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate_id: Annotated[UUID, Field(title="Candidate Id")]
    candidate_index: Annotated[StrictInt, Field(ge=0, title="Candidate Index")]
    error: StageError | None = None
    metaparameters: Annotated[
        TimeOffsetMetaparameters
        | TimeOffsetPassBiasMetaparameters
        | TimeOffsetFrequencyPassBiasMetaparameters
        | MeanElementsTwoParameterMetaparameters,
        Field(discriminator="model", title="Metaparameters"),
    ]
    quality: QualityResult | None = None
    result: BatchResult | None = None
    status: CandidateStatus


class DatasetPacket(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    measurements: Annotated[list[Measurement], Field(title="Measurements")]
    presented_count: Annotated[StrictInt, Field(ge=0, title="Presented Count")]
    provenance: Annotated[dict[str, str], Field(title="Provenance")] = {}
    query: DatasetQuery
    raw_count: Annotated[StrictInt, Field(ge=0, title="Raw Count")]
    rejected_count: Annotated[StrictInt, Field(ge=0, title="Rejected Count")]
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"
    stations: Annotated[dict[str, Cartesian3], Field(title="Stations")]
    tdm: TdmDocument


class QualityRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reference_oem: OemDocument | None = None
    result: BatchResult
    schema_version: Annotated[Literal["0.1"], Field(title="Schema Version")] = "0.1"
    selection_criterion: InformationCriterion


class RunRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attempts: Annotated[StrictInt, Field(ge=0, title="Attempts")]
    candidates: Annotated[list[CandidateRecord], Field(min_length=1, title="Candidates")]
    created_at: Annotated[StrictAwareDatetime, Field(title="Created At")]
    errors: Annotated[list[StageError], Field(title="Errors")] = []
    request_sha256: Annotated[str, Field(title="Request Sha256")]
    run_id: Annotated[UUID, Field(title="Run Id")]
    selected_candidate_id: Annotated[UUID | None, Field(title="Selected Candidate Id")] = None
    status: RunStatus
    updated_at: Annotated[StrictAwareDatetime, Field(title="Updated At")]


class RunResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: Annotated[list[CandidateRecord], Field(min_length=1, title="Candidates")]
    errors: Annotated[list[StageError], Field(title="Errors")] = []
    run_id: Annotated[UUID, Field(title="Run Id")]
    selected_candidate: CandidateRecord
    selected_candidate_id: Annotated[UUID, Field(title="Selected Candidate Id")]
    status: RunStatus
